### ISSUE TITLE
Quiet mode for scripting other than -r

### ISSUE THREAD

**Issue by dmedinag** [mrzool/nordvpn-server-find#6]
It'd be nice to use, for example, the `-l` flag within scripts. At the moment this is not trivial because the output is both colored and suffixed by the current server load.

Current behaviour (fine outside of scripts
```bash
~ nordvpn-server-find -l uk -n 1

Looking for servers located in UK with server load lower than 30%...

ukXXX.nordvpn.com    1%
```

Desired behaviour

```bash
~ nordvpn-server-find -q -l uk -n 1
ukXXX.nordvpn.com
```

**Comment by mrzool** [comment]
Hey @dmedinag, such an option would make a lot of sense, I'll look into it. It might take a while though, because I'm pretty busy at the moment. If you need this earlier and want to give it a shot, feel free to send me a PR!

**Comment by dmedinag** [comment]
Sounds good, might give it a go, thanks!

**Comment by mrzool** [comment]
How would you handle the case where `n`>1 when `-q` is given? Simply uncolored list with linebreaks?
