### ISSUE TITLE
Stop emitting terminal-control sequences when writing to a pipe

### ISSUE THREAD

**Issue by JulianOestreich90** [mrzool/nordvpn-server-find#9]
The program emits terminal-control sequences when writing to a pipe rather than a terminal.

**Comment by mrzool** [comment]
Can you provide the steps to reproduce the issue?

**Comment by JulianOestreich90** [comment]
https://stackoverflow.com/questions/70389953/concatenate-string-from-inside-an-array-to-another-string-in-bash/70404639?noredirect=1#comment124457848_70404639

**Comment by mrzool** [comment]
For scripting the `q` and `r` flags are the way to go, but I agree that the script should check if it's writing to a terminal or a pipe in any case. I'll see what I can do.
